### ISSUE TITLE
Command `lando pull` requests password

### ISSUE THREAD

**Issue by megclaypool** [lando/gitpod#11]
Hey there,

I'm trying to use Lando and Gitpod to sync with a repo on Pantheon. I've pulled the code to GitHub so I can run GitPod, but I need to get the database and files from Pantheon... I used the command `lando pull` (I've got it set up in the .lando.yml to *not* pull code) and was first prompted for a machine token (no problem) and then for a password (for the local environment, I'm pretty sure).

```
gitpod /workspace/PROJECT_NAME (master) $ lando pull
? Enter a Pantheon machine token [hidden]
Attempting to login via terminus...
 [notice] Logging in via machine token.
Logged in as XXX@gmail.com
Verifying that you have access to PROJECT_NAME...
 ------------------ -------------------------------------------------------------------------------------------- 
  ID                 ...redacted...
 ------------------ -------------------------------------------------------------------------------------------- 
Access confirmed!
Pantheon LOCKR setup
dev.aeda4194-aed0-47e8-8c9c-xxxxxxxx@appserver.dev.aeda4194-aed0-47e8-8c9c-xxxxxxxx.drush.in's password: 
```

I've tried nothing (just enter), admin, YES, and my pantheon password (just in case), all to no avail. Do you have any idea what the user password is for this environment???

**Comment by labboy0276** [comment]
@megclaypool try using the `devwithlando/gitpod-source:1` image instead.  I pushed some changes up to the pantheon plugin to fix this and they are not on the stable version yet.
